baseURL = "https://myblog-6vy.pages.dev/"
title = "colorless"
theme = "hextra"

hasCJKLanguage = true

languageCode = "zh-CN"
defaultContentLanguage = "zh-cn"


[params]
description = "colorless 的网络安全学习笔记"


[params.author]
name = "colorless"
email = "2454146361@qq.com"


[markup]
  [markup.highlight]
    noClasses = false


[outputs]
home = ["html", "llms"]
page = ["html", "markdown"]
section = ["html", "rss", "markdown"]


[[menu.main]]
name = "文档"
pageRef = "/docs"
weight = 1


[[menu.main]]
name = "关于"
pageRef = "/about"
weight = 2